version: "3.8"

services:
#  db:
#    image: mongo:latest
#    container_name: db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#    ports:
#      - "27017:27017"
#      - '28017:28017'
#    networks:
#      - mmsNetwork
#    command: >
#      bash -c "mongod --replSet rs0 --bind_ip localhost,db"
#
#  mongo-express:
#    depends_on:
#      - db
#    image: mongo-express
#    ports:
#      - "8081:8081"
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#      ME_CONFIG_MONGODB_URL: mongodb://root:example@db:27017/
#      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
#    networks:
#      - mmsNetwork

  app:
    depends_on:
      - db
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile

  client:
    depends_on:
      - redis
    image: dpapp001/emse-api:latest
    container_name: client
    env_file:
      - .env
    ports:
      - "4000:4000"
      - "5555:5555"
    command: > 
      bash -c "yarn && yarn generate && yarn dev"
    networks:
      - mmsNetwork

  redis:
    container_name: mms_redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - mmsNetwork
networks:
    mmsNetwork: