version: "3.8"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "prisma generate && python app.py"
    networks:
      - mmsNetwork
  api:
    container_name: api
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: >
      bash -c "prisma generate && python3 -m uvicorn api:app --reload --host 0.0.0.0"
    networks:
      - mmsNetwork
  client:
    depends_on:
      - redis
    image: dpapp001/emse-api:latest
    container_name: client
    env_file:
      - .env
    ports:
      - "4000:4000"
    command: > 
      bash -c "yarn && yarn generate && yarn dev"
    networks:
      - mmsNetwork
  redis:
    container_name: mms_redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - mmsNetwork
networks:
    mmsNetwork: