style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/odu-emse/mms
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - chore
        - refactor
        - ci
  commit_groups:
    title_maps:
      feat: Features
      fix: Bug Fixes
      chore: Maintenance
      refactor: Code Refactoring
      ci: Continuous Integration Changes
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE