name: Build and Deploy Docs

on:
  push:
    branches: [ 'dev', 'master', 'ALMP-**' ]

jobs:
  docs:
    runs-on: ubuntu-latest
    name: Create Docs
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.13'
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Set env variables
        run: |
          echo "DATABASE_URL=${{secrets.DATABASE_URL}}" > .env
          echo "DIRECT_URL=${{secrets.DIRECT_URL}}" > .env
      - name: Generate Prisma types
        run: prisma generate
      - name: Generate docs
        run: pdoc --html --output-dir docs --force .
      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/emse-mms